### ISSUE TITLE
How to use tailwind with Svelte

### ISSUE THREAD

**Issue by simonjcarr** [meteor/examples#22]
Thanks for putting these examples up, they are a great starting point.

However, I have started to get excited again about meteor now that I see it has support for Svelte, but no tailwind is a deal-breaker for me. 

Can you add an example of Svelte with Tailwind? Even a Hello World be great, just so I have a starter project, or perhaps advise if it's not possible yet to use a combination of Meteor, Svelte and Tailwind.

Thanks again.

**Comment by vitorflores** [comment]
Hi Simon, we will work on it, it's on our backlog. Thanks for the request.
