### ISSUE TITLE
in tailwindcss example, purge in tailwind.config.js should be filled

### ISSUE THREAD

**Issue by johnsonchandra** [meteor/examples#8]
since it is example of how using tailwindcss, I think it is better to include 

`purge: ['./imports/ui/**/*.{js,jsx,ts,tsx}', './public/*.html']`

instead of 

`purge: []`

imho, just to be as real-world as possible.

**Comment by distalx** [comment]
+1

**Comment by filipenevola** [comment]
thank you, the PR is merged now with this update.
